### PR TITLE
Replaced hoverable and clickable decorators with generic listen_to

### PR DESCRIPTION
**Pull request by AlecAivazis**

### CODE REVIEW

**Comment by AlecAivazis** [comment]
I'm not sure if I see why there is a problem with the state variables. If I understand what's going on then I should be able to reference `this.props.onMouseOver` in replace of  `this.props.hover`, right?

**Comment by aaivazis** [comment]
Now that I look at it more closely it seems that only the functions are called and the state variables are not in fact passed down to the child.

**Comment by AlecAivazis** [comment]
Just wanted to make sure that I'm not missing something here. The EventListener handler only fires the function and does not set a prop, correct? Can't we define the hoverable and clickable components in terms of the EventListener component?

**Comment by mondomishi** [comment]
Correct, `EventListener` is intended to simply fire the handlers defined on its only child. If this worked, we could indeed implement `hoverable` and `clickable` using `EventListener`. However, the current implementation of `EventListener` fails due to the issue of not being able to bind the child's prototype's implementation of the handler to the child.

**Comment by AlecAivazis** [comment]
Alright well I merged the branch because I wanted to use the decorators. I might end up making hover_style today but we'll see how things go. We might want to think about moving the implementation to `EventListener` at some point but there's no rush for now.

**Pull request merged**
